# Generated by Django 3.0.6 on 2020-05-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('header', models.CharField(max_length=122)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
