# Generated by Django 3.0.6 on 2020-05-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200527_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
