# Generated by Django 2.2.8 on 2020-06-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200626_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tag',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='tag',
            field=models.CharField(default='', max_length=122),
        ),
    ]
