# Generated by Django 2.2.8 on 2020-06-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200626_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='organizer',
            field=models.CharField(default='', max_length=122),
        ),
    ]
