# Generated by Django 3.1 on 2020-09-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_eventpage_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='eventday',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='eventmonth',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='eventyear',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='eventdate',
            field=models.IntegerField(default=1),
        ),
    ]
